pipeline:
  name: EKS Deploy
  identifier: EKS_Deploy
  projectIdentifier: AWS
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: EKS Deploy
        identifier: EKS_Deploy
        description: ""
        type: Deployment
        spec:
          deploymentType: ECS
          service:
            serviceRef: ClusterCreation
          environment:
            environmentRef: DEV
            environmentInputs:
              identifier: DEV
              type: PreProduction
              variables:
                - name: SubnetId1
                  type: String
                  value: <+input>
            deployToAll: false
            infrastructureDefinitions:
              - identifier: AWSDEVuseast1
          execution:
            steps:
              - step:
                  type: CreateStack
                  name: CreateStack
                  identifier: CreateStack
                  spec:
                    provisionerIdentifier: ABC
                    configuration:
                      stackName: EKS12
                      connectorRef: AWS
                      region: us-east-1
                      templateFile:
                        type: Remote
                        spec:
                          store:
                            type: Github
                            spec:
                              paths:
                                - aws ekstask
                              connectorRef: GitHub
                              gitFetchType: Branch
                              branch: main
                      roleArn: ""
                      parameterOverrides:
                        - name: EKSNodeGroupName
                          value: <+input>
                          type: String
                        - name: EKSClusterName
                          value: <+input>
                          type: String
                        - name: VpcId
                          value: <+input>
                          type: String
                        - name: SubnetId1
                          value: <+env.variables.SubnetId1>
                          type: String
                        - name: SubnetId2
                          value: <+input>
                          type: String
                  timeout: 20m
            rollbackSteps: []
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
