pipeline:
  name: MyPipeline
  identifier: MyPipeline
  projectIdentifier: AWS
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Cstage
        identifier: Cstage
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: CreateStack
                  name: CreateStack
                  identifier: CreateStack
                  spec:
                    provisionerIdentifier: ABC
                    configuration:
                      stackName: Newone
                      connectorRef: AWS
                      region: ap-southeast-2
                      templateFile:
                        type: Remote
                        spec:
                          store:
                            type: Github
                            spec:
                              paths:
                                - lab1.1.1.yaml
                              connectorRef: GitHub
                              gitFetchType: Branch
                              branch: main
                      roleArn: ""
                      parameterOverrides:
                        - name: NewS3
                          value: harrrr1
                          type: String
                  timeout: 10m
        tags: {}
  variables:
    - name: S3Bucket
      type: String
      description: ""
      required: false
      value: <+input>
